#ifndef DOU_DDGI_PROBE_STATE_INCLUDED
#define DOU_DDGI_PROBE_STATE_INCLUDED

#define DDGI_PROBE_OFF 0u
#define DDGI_PROBE_VIGILANT 1u
#define DDGI_PROBE_UNINITIALIZED 2u
#define DDGI_PROBE_SLEEP 3u
#define DDGI_PROBE_AWAKE 4u
#define DDGI_PROBE_NEW_AWAKE 5u
#define DDGI_PROBE_NEW_VIGILANT 6u

#define DDGI_PROBE_UPDATE 1u
#define DDGI_PROBE_RESET_HISTORY 2u
#define DDGI_PROBE_CLASSIFY 4u
#define DDGI_PROBE_DYNAMIC_NEARBY 8u
#define DDGI_PROBE_STATIC_NEARBY 16u
#endif
